#!/bin/bash
#
# This script automatically generates a configuration file using a defined
# template.
#
# All references of {{HOME}} in the template are replace with the contents of
# the $HOME-variable.

CONF="$HOME/.curlrc"
TMPL="$HOME/.curl/template"

rm -f "$CONF"
echo -e "# This file was generated by $0 on $(date)\n" > $CONF
cat $TMPL | sed "s#{{HOME}}#$HOME#" >> $CONF

chmod 0400 "$CONF"
