# Models
model: mistral/devstral-2512
alias:
  - dev:mistral/devstral-2512 # Agentic tasks
  - code:mistral/codestral-latest # Larger codebases
  - l:mistral/mistral-large-latest # Gen purpose
  - m:mistral/mistral-medium-latest # Gen purpose
  - s:mistral/mistral-small-latest # Gen purpose
weak-model: mistral/mistral-small-latest

# Git
auto-commits: false
show-diffs: false
gitignore: false

# Configuration
read: [AGENTS.md]
vim: true
watch-files: true

# UI
dark-mode: false
code-theme: "native"
user-input-color: "#424868"
tool-error-color: "#f7768e"
tool-warning-color: "#e0af68"
assistant-output-color: "#c0caf5"
completion-menu-color: "#424868"
completion-menu-bg-color: "#121212"
completion-menu-current-color: "#121212"
completion-menu-current-bg-color: "#424868"
