# Models
model: mistral/codestral-latest
weak-model: mistral/mistral-small-latest
alias:
  - code:mistral/codestral-latest
  - large:mistral/mistral-large-latest
  - medium:mistral/mistral-medium-latest
  - small:mistral/mistral-small-latest


# Configuration
read: [AGENTS.md]
vim: true
show-diffs: false
gitignore: true
watch-files: true

# UI
dark-mode: true
completion-menu-color: "#c0caf5"
completion-menu-bg-color: "#121212"
