# Models
model: mistral/devstral-2512
alias:
  - dev:mistral/devstral-2512 # Agentic tasks
  - devm:mistral/devstral-medium-2507 # Agentic tasks
  - devs:mistral/devstral-small-2507 # Agentic tasks
  - code:mistral/codestral-latest # Larger codebases
  - large:mistral/mistral-large-latest # Gen purpose
  - medium:mistral/mistral-medium-latest # Gen purpose
  - small:mistral/mistral-small-latest # Gen purpose
weak-model: mistral/mistral-small-latest

# Git
auto-commits: false
show-diffs: false
gitignore: false

# Configuration
read: [AGENTS.md]
vim: true
watch-files: true

# UI
dark-mode: true
completion-menu-color: "#c0caf5"
completion-menu-bg-color: "#121212"
