alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias la='ls -A'
alias ll='ls -lah'
alias cp='cp -X' # Do NOT copy extended attributes
alias rmallsvn='rm -rf `find . -type d -name .svn`'
alias rmalldsstore='rm -rf `find . -type f -name .DS_Store`'
alias mysql='/usr/local/mysql-5.5.18-osx10.5-x86_64/bin/mysql'
alias dev='cd /Volumes/developers/teun'
alias twc="find . -type f -name '*.php' -exec cat {} \; | wc -l | sed -e 's/^[ \t]*//g'"
alias ttree="find . -not \( -type d -name .svn -prune \) -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"
alias tip='curl ifconfig.me/ip'
