#!/bin/bash
#
# JUMP
# ----
# SSH to a host jumping through other hosts.

if [[ $# -eq 0 ]]; then
	echo -e "Usage: $0 host [host2 [host3 [etc..]]]"
else
	SSH=$(which ssh)
	CMD=""

	# Create command
	for HOST in $*; do
		CMD="$CMD $SSH -tt $HOST"
	done
	CMD=`echo $CMD | sed 's/^\ //g'`

	# Execute
	$CMD
fi
