#!/bin/bash
#
# KNOCK PROXY
# -----------
# Knock a series of ports before proxy-ing to the final port.

if [[ $# < 2 ]]; then
	echo "Usage: $0 host port [knock [knock [knock]]]"
else
	NMAP=$(which nmap)
	NCAT=$(which ncat)
	HOST=$1
	PORT=$2

	shift
	for ARG in "$@"; do
		$NMAP -PN --host_timeout 201 --max-retries 0 -p $ARG $HOST >/dev/null
	done

	$NCAT $HOST $PORT
fi
