#!/bin/bash
#
# Knock a series of ports before proxy-ing to the final port.

if [[ $# < 2 ]]; then
	echo "Usage: $0 host port [knock [knock [knock]]]"
else
	HOST=$1
	PORT=$2

	shift
	for ARG in "$@"; do
		nmap -PN --host_timeout 201 --max-retries 0 -p $ARG $HOST >/dev/null
	done

	ncat $HOST $PORT
fi
