#!/bin/bash
#
# SNIFF
# -----
# Sniff HTTP requests using tcpdump

TCPDUMP=$(which tcpdump)
DEV=$1
HOST=$2
METHOD=$3

if [[ -z "$HOST" ]]; then
	echo -e "Usage: $0 device host [method]"
	exit 1
fi

CMD="(dst $HOST or src $HOST)"

case $METHOD in
	"get" | "GET")
		CMD="$CMD and tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420"
		;;
	"head" | "HEAD")
		CMD="$CMD and tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x48454144"
		;;
	"post" | "POST")
		CMD="$CMD and tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354"
		;;
	*)
		CMD="$CMD and (tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420 or tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x48454144 or tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354)"
esac

$TCPDUMP -i $DEV -s 0 -Aqnn "$CMD"
