#!/bin/bash
#
# SOCKS PROXY
# -----------
# Setup a simple SOCKS Proxy through SSH.
# See: http://people.arsc.edu/~murakami/SSH_SOCKS5_Proxy/

PORT=1234

pid()
{
	# Get the PID of any active SOCKS Proxy
	echo $(ps -ef | grep 'ssh -f2qTnND' | grep -v grep | awk '{print $2}')
}

proxy()
{
	SSH=$(which ssh)
	HOST=$1

	# Setup proxy
	$SSH -f2qTnND $PORT $HOST
}

## Execute

PID=$(pid)

if [[ -z $1 ]]; then
	echo -e "Usage: $0 [host]"
elif [[ -z $PID ]]; then
	proxy $1
fi

PID=$(pid)

if [[ ! -z $PID ]]; then
	echo -e "Proxy running 127.0.0.1:$PORT (pid: $PID)"
fi
