#!/bin/bash
#
# SOCKS5 PROXY
# ------------
# Setup a simple SOCKS Proxy through SSH.
# See: http://people.arsc.edu/~murakami/SSH_SOCKS5_Proxy/

pid()
{
	# Get the PID of any active SOCKS Proxy
	echo $(ps -ef | grep 'ssh -f -C2qTnN -D' | grep -v grep | awk '{print $2}')
}

proxy()
{
	SSH=$(which ssh)
	HOST=$1
	PORT=1234

  # Use default port when not valid
	if [[ $2 =~ ^[1-9][0-9]{2,4}$ ]]; then
		PORT=$2
	fi

	# Setup proxy
	$SSH -f -C2qTnN -D $PORT $HOST
}

## Execute

PID=$(pid)

if [[ -z $1 ]]; then
	echo -e "Usage: $0 [[external host] local port]"
elif [[ -z $PID ]]; then
	proxy $1 $2
fi

PID=$(pid)

if [[ ! -z $PID ]]; then
	echo -e "Proxy running (pid: $PID)"
fi
