#!/bin/bash
# Show info on a given git repository

pushd . >/dev/null

# Find base of git directory
while [ ! -d .git ] && [ ! `pwd` = "/" ]; do cd ..; done

if [ -d .git ]; then

	echo
  echo "REMOTE URL"
	echo "----------"
	git remote -v

	echo
	echo "REMOTE BRANCHES"
	echo "---------------"
	git branch -r

  echo
  echo "CONFIGURATION"
  echo "-------------"
  cat .git/config

  echo
  echo "LOCAL BRANCHES"
  echo "--------------"
  git branch

	echo
	echo "LAST COMMIT"
	echo "-----------"
	git show --name-status

else
  echo "Not a git repository."
fi

popd >/dev/null
